### Testes de rotas UserRoutes
POST /api/users
Content-Type: application/json

{
  "name": "Ruan Pereira",
  "type": "ALUNO",
  "address": "Fortaleza - CE"
}

# Criar usuário
# POST http://localhost:3000/users
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0YzVjODRmZi1mNWUyLTRhMjctOTU2My0wM2E5Yzk3YzM3NzQiLCJyb2xlIjoiRElSRVRPUiIsImlhdCI6MTc2NDE3NzY2MSwiZXhwIjoxNzY0MjY0MDYxfQ.WC0kRcSUmliDsFwhXJ8aJsgc1YsQ1qGpzzH6N5xqlIs

# {
#   "name": "Coordenador teste",
#   "email": "coordenador.cruz@example.com",
#   "password": "senhatopzin123",
#   "role": "COORDENADOR"
# }

# Login
# POST http://localhost:3000/login/auth
# Content-Type: application/json

# {
#   "email": "euzebio.cruz@example.com",
#   "password": "senhatopzin123"
# }

# GET http://localhost:3000/memberships/f73b2b4e-29e9-4bb1-ba86-80dc3de3e1c1
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0YzVjODRmZi1mNWUyLTRhMjctOTU2My0wM2E5Yzk3YzM3NzQiLCJyb2xlIjoiRElSRVRPUiIsImlhdCI6MTc2NDA3MTI1NCwiZXhwIjoxNzY0MTU3NjU0fQ.TImHX10OmQMyidALLOebqqYJ8Mexw2lnzaTfqiDsfiQ

## Listar todos os usuários
# GET http://localhost:3000/users
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0YzVjODRmZi1mNWUyLTRhMjctOTU2My0wM2E5Yzk3YzM3NzQiLCJyb2xlIjoiRElSRVRPUiIsImlhdCI6MTc2MzY3OTA1MywiZXhwIjoxNzYzNzY1NDUzfQ.Cp56WKWuFgueNGOkxq6e4TeJjbpjiout-KduwxBdFlA

### Restore User
# PATCH http://localhost:3000/users/eb4dd2cf-8aa2-4b37-8b86-1a6da9b03525/restore

### Paginação
# GET http://localhost:3000/users/pagination?page=1&pageSize=4

### Retorna por ID
# GET http://localhost:3000/users/4c5c84ff-f5e2-4a27-9563-03a9c97c3774
# Authorization: Bearer SEU_TOKEN_AQUI

### Update de usuário
# PUT http://localhost:3000/users/4a903605-f604-4518-8e5a-51431a987992
# Content-Type: application/json
#
# {
#   "name": "Ruan Pereira updated",
#   "email": "ruan.top@example.com",
#   "password": "senha12356786",
#   "role": "MEMBRO"
# }

# PUT http://localhost:3000/user/me
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmYWEyOTIyYy1jY2FmLTQzMDgtYTViNi0wOTY0MTE0YTIyZmUiLCJyb2xlIjoiTUVNQlJPIiwiaWF0IjoxNzYzOTk4Mzg1LCJleHAiOjE3NjQwODQ3ODV9.KF0dVDxLMj24uE4Q5_WBBJFonq5uVmboZuyK9XcZwCA
# {
#     "name": "New Name"
# }

### Delete User
# DELETE http://localhost:3000/users/8f97dc4c-254d-40d3-9c9f-346a363d1e7b
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0YzVjODRmZi1mNWUyLTRhMjctOTU2My0wM2E5Yzk3YzM3NzQiLCJyb2xlIjoiRElSRVRPUiIsImlhdCI6MTc2NDAwMTAwMywiZXhwIjoxNzY0MDg3NDAzfQ.hd5RBKVvhggSeWp7gXIf1EWBJW35JViHMS51kEBoluo

# Criar Membership (Join Project)
# POST http://localhost:3000/memberships/join
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0YzVjODRmZi1mNWUyLTRhMjctOTU2My0wM2E5Yzk3YzM3NzQiLCJyb2xlIjoiRElSRVRPUiIsImlhdCI6MTc2NDQyNDcyMCwiZXhwIjoxNzY0NTExMTIwfQ.KzriiJKxjOiKcU6yYVRel-CoaeRyF2cslhajV6jReaw

# {
#   "userId": "79f9a614-7c05-4db5-b129-ce7fc1d8e834",
#   "projectId": "80242abc-8ba1-4ac7-b81a-76839e2b3fdd"
# }

# GET http://localhost:3000/memberships
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmNzdkZjc0Ny03OTE0LTRjODEtODRlZS02NjI5ZjgyOTQ2NzYiLCJyb2xlIjoiQ09PUkRFTkFET1IiLCJpYXQiOjE3NjQzODcxODEsImV4cCI6MTc2NDQ3MzU4MX0.ok-8OWOEaDOrIqhmA__jt-TPDQZubrT756o1epOUfWk
# ## Adicionar membro corretamente
# POST http://localhost:3000/projects/298d471d-2a3f-43eb-b5d3-c730112e75d1/coordenador/e7261645-c402-4994-b758-96600a03d172/add/79f9a614-7c05-4db5-b129-ce7fc1d8e834
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlNzI2MTY0NS1jNDAyLTQ5OTQtYjc1OC05NjYwMGEwM2QxNzIiLCJyb2xlIjoiQ09PUkRFTkFET1IiLCJpYXQiOjE3NjQyMDMxNzMsImV4cCI6MTc2NDI4OTU3M30.l18BwtxFNGfAwZgdPCAvaqN9rnA8i5J6gwkCBdnMSbc

# PUT http://localhost:3000/project/4c3f9985-13e1-467e-97db-7ceb88dccc26/coordenador/faa2922c-ccaf-4308-a5b6-0964114a22fe/edit/4c3f9985-13e1-467e-97db-7ceb88dccc26
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmYWEyOTIyYy1jY2FmLTQzMDgtYTViNi0wOTY0MTE0YTIyZmUiLCJyb2xlIjoiTUVNQlJPIiwiaWF0IjoxNzY0MzczNTQ4LCJleHAiOjE3NjQ0NTk5NDh9.uOB8FTOq4KzpHUElqvHxbH_v_T-5GYooXkCgHxMY4Z8
# Content-Type: application/json

# {
#   "name": "Novo nome editado do projeto",
#   "status": "PLANEJADO",
#   "description": "Descrição atualizada 2 do projeto",
#   "goals": "Metas atualizadas 2 do projeto"
# }

# DELETE /project/298d471d-2a3f-43eb-b5d3-c730112e75d1/coordenador/e7261645-c402-4994-b758-96600a03d172/remove/faa2922c-ccaf-4308-a5b6-0964114a22fe
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmNzdkZjc0Ny03OTE0LTRjODEtODRlZS02NjI5ZjgyOTQ2NzYiLCJyb2xlIjoiQ09PUkRFTkFET1IiLCJpYXQiOjE3NjQzODcxODEsImV4cCI6MTc2NDQ3MzU4MX0.ok-8OWOEaDOrIqhmA__jt-TPDQZubrT756o1epOUfWk



# "email": "coordenador.cruz@example.com",
# "password": "senhatopzin123"


	
# Response body
# Download
# {
#   "_traceId": "aec212ab-2922-4073-961e-aeb1db491e15",
#   "_success": true,
#   "_data": {
#     "_isActive": true,
#     "_deletedAt": null,
#     "_createdAt": "2025-12-04T17:27:30.776Z",
#     "_updatedAt": "2025-12-04T17:27:30.776Z",
#     "_id": "b0062c28-fefe-4bf6-bcf0-9799a25f9805",
#     "_name": "New Member",
#     "_email": {
#       "_email": "member@example.com"
#     },
#     "_password": {
#       "_password": "$2b$10$.2bwc549pWzNMvL7lFyYYOWEuW6pIVUQ2vBgDz0S/w5XvUgKZJPEC"
#     },
#     "_role": "MEMBRO"
#   },
#   "_errors": null
# }


# {
#   "name": "Membership teste atualizado",
#   "email": "testemembership.cruz@example.com",
#   "password": "senhatopzin123",
#   "role": "MEMBRO"
# }